title: A test blog is a happy blog
author: lvolkmann
email: hello@landonvolkmann.com
description: > # this means to ignore newlines until "baseurl:"
  Handy little description of the blog

# social links
twitter_username: landonvolkmann # DO NOT include the @ character, or else the build will fail!
github_username:  lvolkmann # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
